CREATE TABLE [dbo].[Reviews]
(
	[ReviewID] INT IDENTITY(2000,1) PRIMARY KEY,
	[UserID] INT NOT NULL FOREIGN KEY REFERENCES Users(UserID),
	[CarID] INT NOT NULL FOREIGN KEY REFERENCES Car_details(CarID),
	[Validation] NVARCHAR(50) NULL,
	[Comment] NVARCHAR(MAX) NULL,
)